apiVersion: apps/v1
kind: Deployment
metadata:
  name: expense-tracker-app
  labels:
    app: expense-tracker-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: expense-tracker-app
  template:
    metadata:
      labels:
        app: expense-tracker-app
    spec:
      containers:
        - name: expense-tracker-app
          image: public.ecr.aws/e2v5f4o0/expense-tracker:latest
          ports:
            - containerPort: 8080

---
apiVersion: v1
kind: Service
metadata:
  name: expense-tracker-service
spec:
  selector:
    app: expense-tracker-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: LoadBalancer